version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user_tu_salon_cut
      - POSTGRES_DB=tu_salon_cut
      - PGDATA=/data/db
    volumes:
      - db:/data/db
    expose:
      - 5432
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U user_tu_salon_cut -d tu_salon_cut

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    command: sh -c "yarn install && yarn start:dev"
    restart: always
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=user_tu_salon_cut
      - DB_DATABASE=tu_salon_cut
      - DB_HOST=db
      - DB_CLIENT=postgres
    volumes:
      - ./:/home/node/app
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    command: sh -c "yarn install && yarn start:dev"
    restart: always
    volumes:
      - ./:/home/node/app
    ports:
      - '3000:3000'

volumes:
  db:
    driver: local
